"""
Preset quiz bank: exactly 20 questions per career role.

Each entry is:
    (skill name, question, [4 options], index of correct option, explanation)

Skill names must match the names in seed.py. The server shuffles question
order and option order on every attempt, so the set stays preset but the
quiz feels different each time.
"""

QUESTION_BANK = {
    "Data Analyst": [
        ("SQL", "Which clause filters groups after GROUP BY has been applied?",
         ["WHERE", "HAVING", "FILTER", "ORDER BY"], 1,
         "HAVING filters aggregated groups. WHERE filters individual rows before grouping."),
        ("SQL", "Which join returns every row from the left table, even without a match on the right?",
         ["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "SELF JOIN"], 1,
         "A LEFT JOIN keeps all left rows and fills unmatched right columns with NULL."),
        ("SQL", "How does COUNT(*) differ from COUNT(column)?",
         ["COUNT(*) ignores duplicates", "COUNT(*) counts rows including NULLs",
          "COUNT(column) counts rows including NULLs", "They are always identical"], 1,
         "COUNT(*) counts every row. COUNT(column) skips NULL values in that column."),
        ("Python", "What is the output of len([1, 2, 3, 2])?",
         ["3", "4", "2", "Error"], 1,
         "len counts every element, duplicates included."),
        ("Python", "What does [x * x for x in range(4)] produce?",
         ["[1, 4, 9, 16]", "[0, 1, 4, 9]", "[0, 1, 2, 3]", "[0, 2, 4, 6]"], 1,
         "range(4) yields 0 to 3, and each value is squared."),
        ("Pandas", "What does df.dropna() do by default?",
         ["Fills missing values with zero", "Removes rows containing missing values",
          "Removes columns with any value", "Sorts the DataFrame"], 1,
         "dropna removes rows that contain at least one missing value by default."),
        ("Pandas", "What does df.groupby('city')['sales'].sum() return?",
         ["The sum of all rows", "Total sales for each city", "The list of cities",
          "The average sales per city"], 1,
         "groupby splits the data by city, then sums sales within each group."),
        ("Power BI", "When is a DAX measure calculated?",
         ["When the file is saved", "At query time, based on the filter context",
          "Only during the first load", "Once per table row at import"], 1,
         "Measures are evaluated when a visual asks for them, using the current filters."),
        ("Power BI", "What is the main purpose of a slicer?",
         ["To change the data source", "To let users filter visuals on a page",
          "To write DAX formulas", "To export a report"], 1,
         "Slicers give viewers an interactive filter that affects the connected visuals."),
        ("Statistics", "What is the median of 1, 3, 5, and 100?",
         ["3", "4", "5", "27.25"], 1,
         "With an even count, the median is the mean of the two middle values: (3 + 5) / 2 = 4."),
        ("Statistics", "Which measure is most affected by an extreme outlier?",
         ["Median", "Mode", "Mean", "Interquartile range"], 2,
         "The mean moves toward outliers. The median is robust to them."),
        ("Statistics", "A p-value of 0.03 means that:",
         ["There is a 97% chance the hypothesis is true",
          "If the null hypothesis were true, a result this extreme would occur about 3% of the time",
          "The effect is 3% large", "The sample was 3% wrong"], 1,
         "The p-value is the probability of data this extreme, assuming the null hypothesis holds."),
        ("Data Modeling", "In a star schema, what does the central fact table typically store?",
         ["Descriptive names and labels", "Measurable events and foreign keys to dimensions",
          "Only user login details", "Only dates"], 1,
         "Fact tables hold numeric measures and keys that link to descriptive dimension tables."),
        ("Data Modeling", "Dimension tables mainly contain:",
         ["Measurable numbers such as revenue", "Descriptive attributes such as product name or region",
          "Transaction logs only", "Foreign keys only"], 1,
         "Dimensions describe the who, what, where, and when of the facts."),
        ("PostgreSQL", "Which command shows the execution plan of a query?",
         ["SHOW PLAN", "EXPLAIN", "DESCRIBE", "PROFILE"], 1,
         "EXPLAIN (and EXPLAIN ANALYZE for real timings) shows how Postgres runs a query."),
        ("PostgreSQL", "What is the main benefit of an index?",
         ["Faster writes on every table", "Faster lookups on the indexed columns",
          "Smaller storage size", "Automatic backups"], 1,
         "Indexes speed up searches, at the cost of extra storage and slower writes."),
        ("Git & GitHub", "Which command stages all changes in the current folder?",
         ["git commit -a", "git add .", "git push", "git save"], 1,
         "git add . stages all modified and new files for the next commit."),
        ("Git & GitHub", "What does git clone do?",
         ["Creates a new empty repository", "Copies a remote repository to your computer",
          "Deletes a branch", "Merges two branches"], 1,
         "git clone downloads a full copy of a repository, including its history."),
        ("Communication", "When presenting a metric to executives, what should come first?",
         ["The full methodology", "The headline insight and recommendation",
          "A list of all data sources", "Raw tables"], 1,
         "Executives want the conclusion first, with supporting detail after."),
        ("Communication", "Which practice makes a dashboard easier to understand?",
         ["Using as many colors as possible",
          "Adding a clear title and a one-sentence takeaway per chart",
          "Showing every column", "Hiding the axes"], 1,
         "Clear titles and takeaways help a viewer read a chart quickly."),
    ],

    "Analytics Engineer": [
        ("SQL", "What does ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) do?",
         ["Removes duplicate rows", "Numbers rows within each customer without collapsing them",
          "Joins two tables", "Creates an index"], 1,
         "Window functions compute values across related rows while keeping every row."),
        ("SQL", "How does UNION ALL differ from UNION?",
         ["UNION ALL removes duplicates", "UNION ALL keeps duplicates and runs faster",
          "They are identical", "UNION ALL only works on numbers"], 1,
         "UNION removes duplicate rows, which costs extra work. UNION ALL keeps them all."),
        ("SQL", "Why use a CTE (a WITH clause)?",
         ["It permanently stores data", "It names an intermediate result to make queries readable",
          "It creates a new database user", "It speeds up every query"], 1,
         "CTEs name intermediate steps so complex queries are easier to read and maintain."),
        ("dbt", "What does ref('orders') do in dbt?",
         ["Deletes the orders model", "Points to another model and builds the dependency graph",
          "Imports a CSV from the internet", "Creates a new database"], 1,
         "ref() links models together, which lets dbt work out the build order."),
        ("dbt", "Which layer typically does light cleanup, renaming, and type casting of raw source tables?",
         ["Marts", "Staging", "Seeds", "Snapshots"], 1,
         "Staging models are one-to-one with sources and apply basic cleanup."),
        ("dbt", "What does the unique test check?",
         ["That a column has no duplicate values", "That a column is sorted",
          "That the table has no columns", "That data is encrypted"], 0,
         "The unique test fails if any value appears more than once in the column."),
        ("dbt", "What does materialized='table' do compared with a view?",
         ["Stores the query result physically, so reads are faster", "Stores only the SQL text",
          "Deletes the view", "Makes the model read-only"], 0,
         "Tables store results, so they cost storage but read quickly. Views re-run the query each time."),
        ("Data Modeling", "What is the grain of a fact table?",
         ["The total number of columns", "What one row represents, such as one order line",
          "The data type of the primary key", "The number of joins allowed"], 1,
         "Defining the grain first is the most important modeling decision."),
        ("Data Modeling", "What is a surrogate key?",
         ["A key copied from the source system",
          "A generated, meaningless key used to identify dimension rows",
          "A password for the database", "A foreign key that points to nothing"], 1,
         "Surrogate keys stay stable even when source system keys change."),
        ("Data Modeling", "A Type 2 slowly changing dimension keeps history by:",
         ["Overwriting old values", "Adding a new row for each change with validity dates",
          "Deleting changed rows", "Storing history in a separate file"], 1,
         "Each version of the record gets its own row, so past reports stay accurate."),
        ("PostgreSQL", "Which type stores semi-structured JSON efficiently in Postgres?",
         ["VARCHAR(1)", "JSONB", "INTEGER", "BOOLEAN"], 1,
         "JSONB stores parsed JSON in a binary form that supports indexing."),
        ("PostgreSQL", "What does VACUUM do?",
         ["Deletes the database", "Reclaims space from dead row versions",
          "Creates backups", "Encrypts tables"], 1,
         "Updates and deletes leave dead row versions behind. VACUUM cleans them up."),
        ("Python", "What does dict.get('key', 0) return if the key is missing?",
         ["None", "0", "An error", "The string 'key'"], 1,
         "get returns the default value instead of raising a KeyError."),
        ("Python", "What is a generator in Python?",
         ["A function that uses yield to produce values lazily",
          "A class that cannot be instantiated", "A type of list", "A database driver"], 0,
         "Generators produce one value at a time, which saves memory on large data."),
        ("Pandas", "df.merge() in pandas is most similar to which SQL operation?",
         ["GROUP BY", "JOIN", "ORDER BY", "UNION"], 1,
         "merge combines two DataFrames on matching keys, like a SQL join."),
        ("Pandas", "What does df.fillna(0) do?",
         ["Removes rows with zeros", "Replaces missing values with 0", "Counts zeros", "Sorts by zero"], 1,
         "fillna replaces NaN values with the value you give it."),
        ("Git & GitHub", "What does git branch feature-x create?",
         ["A new commit", "A new branch named feature-x", "A tag", "A new repository"], 1,
         "git branch creates a branch pointer. Use git switch to move onto it."),
        ("Git & GitHub", "What is git pull?",
         ["Fetch plus merge from the remote", "Push local changes", "Delete remote branches",
          "Create a tag"], 0,
         "git pull fetches remote changes and merges them into your current branch."),
        ("Power BI", "What is Power Query used for?",
         ["Creating dashboards", "Transforming and cleaning data before modeling",
          "Sending emails", "Writing Python code"], 1,
         "Power Query is the transformation layer where data is shaped before it reaches the model."),
        ("Communication", "What belongs in good model documentation?",
         ["Only the author's name", "Purpose, grain, column definitions, and known caveats",
          "Nothing, the code is enough", "Screenshots only"], 1,
         "Documentation lets other people use the model correctly without asking you."),
    ],

    "Data Engineer": [
        ("Python", "Why use a generator when reading a huge file?",
         ["It loads the whole file into memory", "It processes one item at a time, saving memory",
          "It makes the file smaller", "It encrypts the data"], 1,
         "Generators keep only the current item in memory, which suits large files."),
        ("Python", "Which Python collection is immutable?",
         ["list", "dict", "set", "tuple"], 3,
         "Tuples cannot be changed after creation."),
        ("SQL", "Which join returns only rows that match in both tables?",
         ["LEFT JOIN", "INNER JOIN", "FULL OUTER JOIN", "RIGHT JOIN"], 1,
         "INNER JOIN keeps only rows with matches on both sides."),
        ("SQL", "Which Postgres clause inserts a row, or updates it if the key already exists?",
         ["ON CONFLICT", "ON DUPLICATE", "MERGE INTO only", "UPSERT ALL"], 0,
         "INSERT ... ON CONFLICT DO UPDATE makes loads safe to repeat."),
        ("PostgreSQL", "Which command loads a CSV file into a table in bulk?",
         ["COPY", "SELECT INTO", "LOAD DATA", "IMPORT TABLE"], 0,
         "COPY is the fastest built-in way to bulk load files into Postgres."),
        ("PostgreSQL", "Which constraint stops duplicate values in a column?",
         ["CHECK", "UNIQUE", "DEFAULT", "NOT NULL"], 1,
         "UNIQUE rejects any row that repeats a value already in the column."),
        ("ETL Pipelines", "What makes a pipeline idempotent?",
         ["It runs faster each time", "Running it again gives the same result without duplicates",
          "It never fails", "It only runs once a year"], 1,
         "Idempotent pipelines can be safely re-run after a failure."),
        ("ETL Pipelines", "In ELT, when is the data transformed?",
         ["Before loading, outside the warehouse", "After loading, inside the warehouse",
          "Never", "Only by hand"], 1,
         "ELT loads raw data first, then transforms it using the warehouse's compute."),
        ("ETL Pipelines", "What is an incremental load?",
         ["Reloading all data every time", "Loading only rows new or changed since the last run",
          "Loading one row at a time forever", "Deleting old data"], 1,
         "Incremental loads use a watermark, such as an updated_at timestamp, to limit the work."),
        ("Apache Airflow", "What does a DAG define in Airflow?",
         ["Only the database schema", "Tasks and the dependencies between them, with no cycles",
          "User login rules", "Docker images"], 1,
         "A DAG is a directed acyclic graph of tasks and the order they run in."),
        ("Apache Airflow", "What does the retries setting on a task do?",
         ["Deletes failed runs", "Reruns the task automatically after a failure",
          "Changes the schedule", "Logs the user out"], 1,
         "Retries help the pipeline recover from temporary failures such as network glitches."),
        ("Apache Spark", "Which Spark operation triggers actual computation?",
         ["filter", "select", "An action such as count() or show()", "map"], 2,
         "Transformations are lazy. Spark only computes when an action asks for a result."),
        ("Apache Spark", "Why does Spark partition data?",
         ["To compress it", "To spread work across executors in parallel",
          "To encrypt it", "To remove duplicates"], 1,
         "Partitions let many executors process pieces of the data at the same time."),
        ("Docker", "What is the difference between a Docker image and a container?",
         ["They are the same thing", "An image is a template, a container is a running instance of it",
          "A container is a template, an image is a running instance", "Images run only on Windows"], 1,
         "You build an image once, then start as many containers from it as you need."),
        ("Docker", "Which file defines how to build a Docker image?",
         ["docker.yml", "Dockerfile", "compose.json", "build.ini"], 1,
         "A Dockerfile lists the steps that produce the image."),
        ("Git & GitHub", "What does a .gitignore file do?",
         ["Ignores Git itself", "Lists files Git should not track", "Stores passwords", "Deletes branches"], 1,
         "Use it to keep secrets, build output, and local environment files out of the repository."),
        ("Cloud Basics", "What is Amazon S3 mainly used for?",
         ["Running virtual machines", "Object storage for files and data", "Sending emails",
          "Managing DNS"], 1,
         "S3 stores files as objects in buckets, and data lakes often sit on top of it."),
        ("Linux & Shell", "Which command shows running processes?",
         ["ls", "ps", "cd", "mkdir"], 1,
         "ps lists processes. top gives a live view."),
        ("Data Modeling", "What does a fact table primarily hold?",
         ["Descriptions only", "Measures and foreign keys to dimensions",
          "Only user passwords", "Nothing but dates"], 1,
         "Fact tables record measurable events along with links to descriptive dimensions."),
        ("Data Structures & Algorithms", "What is the time complexity of binary search on a sorted array?",
         ["O(n)", "O(log n)", "O(n²)", "O(1)"], 1,
         "Each step halves the remaining search space, which gives logarithmic time."),
    ],

    "Backend Developer (Python)": [
        ("Python", "What is the main difference between a list and a tuple?",
         ["Tuples are mutable, lists are not", "Lists are mutable, tuples are not",
          "They are identical", "Tuples can only hold numbers"], 1,
         "Lists can change after creation. Tuples are fixed."),
        ("Python", "What does *args allow in a function?",
         ["Passing a variable number of positional arguments", "Passing keyword arguments only",
          "Making a function faster", "Importing modules"], 0,
         "*args collects any number of extra positional arguments into a tuple."),
        ("Python", "What is a decorator?",
         ["A function that wraps another function to extend its behavior", "A way to color code",
          "A type of loop", "A database index"], 0,
         "Decorators add behavior such as logging or authentication without changing the function body."),
        ("Python", "What does the with statement do with a file?",
         ["Opens it in read-only mode forever", "Ensures it is closed automatically after the block",
          "Deletes it", "Compresses it"], 1,
         "The context manager guarantees cleanup, even if an error happens."),
        ("FastAPI", "What does a Pydantic model do in FastAPI?",
         ["Styles the HTML", "Validates and parses request data against a schema",
          "Creates database tables", "Routes traffic"], 1,
         "Pydantic models check incoming data and return clear errors when it's wrong."),
        ("FastAPI", "How does FastAPI know a parameter is a path parameter?",
         ["It must be named id", "It appears in the route path in curly braces",
          "It is always the first argument", "It is a global variable"], 1,
         "A name in {braces} in the route path becomes a path parameter."),
        ("FastAPI", "What is Depends used for?",
         ["Dependency injection, such as providing a database session to a route",
          "Deleting dependencies", "Installing packages", "Creating CSS"], 0,
         "Depends lets FastAPI build and pass in shared resources for each request."),
        ("REST API Design", "Which HTTP method should be safe and read-only?",
         ["POST", "DELETE", "GET", "PATCH"], 2,
         "GET retrieves data without changing it."),
        ("REST API Design", "Which status code means a resource was created?",
         ["200", "201", "204", "301"], 1,
         "201 Created is the standard response to a successful POST that creates something."),
        ("REST API Design", "What is the difference between PUT and PATCH?",
         ["PUT replaces the whole resource, PATCH updates part of it",
          "PATCH replaces the whole resource, PUT updates part of it",
          "They are the same", "PUT is only for deleting"], 0,
         "PUT sends the complete new version. PATCH sends only the fields that change."),
        ("PostgreSQL", "What is the trade-off of adding an index?",
         ["Faster reads but slower writes and more storage", "Slower reads but faster writes",
          "No trade-off", "Only storage increases"], 0,
         "Every write must also update the indexes, so indexes are chosen with care."),
        ("PostgreSQL", "What does a foreign key guarantee?",
         ["Each row has a unique name", "Referenced rows exist, which keeps relationships valid",
          "Data is encrypted", "Rows are sorted"], 1,
         "Foreign keys stop orphaned rows from pointing at records that don't exist."),
        ("PostgreSQL", "What does a transaction rollback do?",
         ["Undoes all changes made in the transaction", "Commits the changes",
          "Deletes the table", "Creates a backup"], 0,
         "Rollback keeps the database consistent when part of a multi-step change fails."),
        ("Git & GitHub", "What causes a merge conflict?",
         ["Two branches change the same lines differently", "Pushing too often",
          "Using a long branch name", "Deleting a tag"], 0,
         "Git cannot decide which change to keep, so it asks you to resolve the conflict."),
        ("Git & GitHub", "What does git rebase do?",
         ["Rewrites commits onto a new base to keep history linear", "Deletes all history",
          "Creates a new repository", "Uploads files"], 0,
         "Rebase replays your commits on top of another branch, producing a cleaner history."),
        ("Docker", "What does the CMD instruction in a Dockerfile specify?",
         ["The default command run when a container starts", "The base image only",
          "The port to open on the host", "The author"], 0,
         "CMD sets the default process for the container."),
        ("Linux & Shell", "Which command shows running processes?",
         ["ps", "cp", "touch", "echo"], 0,
         "ps lists the processes currently running on the system."),
        ("Data Structures & Algorithms", "What is the average lookup time in a hash map?",
         ["O(1)", "O(n)", "O(n log n)", "O(n²)"], 0,
         "Hashing jumps straight to the bucket, so lookups are constant time on average."),
        ("Data Structures & Algorithms", "Which data structure follows last-in, first-out order?",
         ["Queue", "Stack", "Tree", "Graph"], 1,
         "A stack adds and removes items from the same end."),
        ("Cloud Basics", "What does IAM control in a cloud account?",
         ["Who can access which resources and what they can do", "Internet speed",
          "Monitor brightness", "Compile code"], 0,
         "Identity and access management defines permissions for users and services."),
    ],

    "Frontend Developer (React)": [
        ("JavaScript", "What is the main difference between let and var?",
         ["let is block scoped, var is function scoped", "let is global only",
          "They are identical", "var cannot be reassigned"], 0,
         "let stays inside the block it is declared in. var leaks out to the whole function."),
        ("JavaScript", "What does === check?",
         ["Value only, with type conversion", "Value and type, with no conversion",
          "Reference only", "Length only"], 1,
         "=== compares both value and type, unlike ==, which converts types first."),
        ("JavaScript", "What is a closure?",
         ["A function that remembers variables from its outer scope", "A way to close the browser",
          "A CSS property", "A loop type"], 0,
         "Closures keep access to variables from where the function was created."),
        ("JavaScript", "What does an async function always return?",
         ["A number", "A Promise", "undefined", "A string"], 1,
         "Even if you return a plain value, an async function wraps it in a Promise."),
        ("JavaScript", "What does array.map() return?",
         ["The original array modified in place", "A new array of transformed values",
          "A single number", "Nothing"], 1,
         "map builds a new array and leaves the original untouched."),
        ("React", "What does useState return?",
         ["Only the value", "An array with the current value and a setter function",
          "An object with a render method", "A promise"], 1,
         "Destructure it as const [value, setValue] = useState(initial)."),
        ("React", "Why does a list need a key prop?",
         ["To set colors", "To help React track which items changed",
          "To sort the list", "It is optional and has no purpose"], 1,
         "Stable keys let React update only the items that changed."),
        ("React", "What does a useEffect cleanup function do?",
         ["Runs before the component mounts",
          "Runs before the next effect or when the component unmounts",
          "Deletes state", "Renders the component"], 1,
         "Cleanup removes subscriptions, timers, and listeners so they don't leak."),
        ("React", "Why must you not mutate props?",
         ["Props are owned by the parent and should be treated as read-only",
          "Props are stored in localStorage", "It makes CSS fail", "It is allowed and recommended"], 0,
         "Data flows down from parent to child. Changing props breaks that flow."),
        ("React", "What does an empty dependency array [] in useEffect mean?",
         ["Run after every render", "Run once after the first render", "Never run",
          "Run only on click"], 1,
         "An empty array tells React the effect depends on nothing, so it runs once on mount."),
        ("REST API Design", "What does HTTP status 404 mean?",
         ["Server error", "Resource not found", "Unauthorized", "Success"], 1,
         "404 Not Found means the server cannot find what the URL points to."),
        ("REST API Design", "Which HTTP method is used to read data?",
         ["POST", "GET", "DELETE", "PUT"], 1,
         "GET retrieves data. POST sends new data."),
        ("Git & GitHub", "What does git commit do?",
         ["Uploads to GitHub", "Saves a snapshot of staged changes locally",
          "Deletes changes", "Creates a branch"], 1,
         "A commit records staged changes in your local history. Push sends them to GitHub."),
        ("Git & GitHub", "What does git stash do?",
         ["Permanently deletes changes", "Temporarily sets aside uncommitted changes",
          "Renames a branch", "Pushes to the remote"], 1,
         "Stash lets you switch tasks without committing half-finished work."),
        ("Git & GitHub", "What does git checkout -b new-branch do?",
         ["Deletes a branch", "Creates and switches to a new branch", "Merges branches",
          "Shows history"], 1,
         "The -b flag creates the branch and switches to it in one step."),
        ("Data Structures & Algorithms", "What is the time complexity of two nested loops over n items?",
         ["O(n)", "O(n log n)", "O(n²)", "O(1)"], 2,
         "Nested loops multiply the work: n times n steps."),
        ("Data Structures & Algorithms", "Which data structure is first-in, first-out?",
         ["Stack", "Queue", "Heap only", "Tree"], 1,
         "A queue processes items in the order they arrived."),
        ("Data Structures & Algorithms", "Binary search requires the data to be:",
         ["Sorted", "Unique", "Small", "Numeric only"], 0,
         "Binary search compares the middle value, which only works when the data is in order."),
        ("Communication", "What makes a strong project case study?",
         ["Problem, approach, and measurable result", "Only the code",
          "A list of technologies only", "A long history of the author"], 0,
         "Recruiters want to see what you solved, how you solved it, and what changed."),
        ("Communication", "What is a good commit message?",
         ["'stuff'", "A short imperative summary such as 'Add login form'", "A full novel", "Emoji only"], 1,
         "Commit messages describe what the change does, in a short imperative sentence."),
    ],
}
